project:
  type: website
  output-dir: _site

website:
  title: "Emily Nordmann"
  site-url: "https://www.emilynordmann.com/"
  description: "Professor Emily Nordmann, Associate Dean of Learning and Teaching at the University of Glasgow. Research on lecture capture, evidence-informed education, and open science."
  favicon: images/headshot_2025.jpg
  open-graph: true
  twitter-card:
    card-style: summary_large_image
  image: images/headshot_2025.jpg
  navbar:
    left:
      - text: "Blog"
        href: post.qmd
      - text: "Contact"
        href: contact.qmd
      - text: "CV"
        href: files/cv.pdf

resources:
  - garden-of-forking-paths.html
  - _redirects
  - "images/**"
  - "files/**"

format:
  html:
    toc: false
    css: styles.css
    theme:
      light: cosmo
      dark: slate

execute:
  freeze: auto
  warning: false
  message: false

lang: en
date-format: long