project:
  type: website
  output-dir: _site

website:
  title: "Emily Nordmann"
  site-url: "https://www.emilynordmann.com/"
  navbar:
    left:
      - text: "Blog"
        href: post.qmd
      - text: "Contact"
        href: contact.qmd
      - text: "CV"
        href: files/cv.pdf

resources:
  - garden-of-forking-paths.html
  - "images/**"
  - "files/**"

format:
  html:
    toc: false
    css: styles.css
    theme:
      light: cosmo
      dark: slate

execute:
  freeze: auto
  warning: false
  message: false

lang: en
date-format: long