[build]
command = "quarto render"
publish = "_site"

[[plugins]]
package = "netlify-plugin-r"     # installs R on Netlify build image

[[plugins]]
package = "@quarto/netlify-plugin-quarto"
  [plugins.inputs]
  version = "latest"
