---
title: "In defence of the essay (or why everyone on the internet is wrong)"
format: html
author: Emily Nordmann
date: '2025-10-12'
slug: essay-defence
---

This blog is a spiritual sequel to our paper "Lecture rapture", where we argued in defence of the lecture as a format. The tldr version is that whilst sometimes your class should be a flipped classroom or small-group active learning session, sometimes, it should be a lecture and there's nothing inherent in the format that makes it bad, as with any form of teaching, it's about the application and execution. This blog is not, however, written in the professional style of that paper. I don't know why I've decided I have so many opinions about this on a Sunday evening but I do, so strap in.

If you'd told baby Emily she'd grow up to spend her career defending tradition, she'd have flipped her box-dyed black emo hair out the way so you could see her roll her kohl-lined eyes before she got back to writing about not fitting in. But I am trying to be nicer to baby Emily these days so instead I'm going to frame this not as defending tradition, but rather as shouting at people who don't know what they're talking about. And baby Emily would be on-board with that.

As I imagine is the case for any academic with a social media account, I have lost track of the number of posts I've seen sagely asserting that the problem with Gen AI and universities isn't AI, it's that everything about higher education is wrong and we just need authentic assessment and to trust students.

OH GO AND GET IN THE SEA.

The assessment that comes most frequently under attack is the traditional essay. We are eruditely informed that AI has highlighted its failings, not caused them, and even if AI disappeared tomorrow, the essay has no place in modern higher education. Instead, we must co-create authentic assessments that allow students to demonstrate the application of their skills and knowledge regardless of whether they use AI. "How do we do that?" we ask in response. "I'm sorry, I can't hear you" the sage replies, "I'm too busy drawing the rest of the fucking owl". 

I am by no means the first, second, or even third person to write a rebuttal against the "death of the essay"  but I do think I have two things that make my particular argument worth writing and worth reading. First, I am a cognitive psychologist. My deep despair with the discussion about AI and education at the moment is that it seems to me that no-one who understands anything about the cognitive principles that underlie how we learn has as a voice. And second, I was first year lead for the best part of a decade and my extremely rough estimate is that I have first marked / moderated / adminstered ~6000 essays in that time and I also designed and taught the tutorials that taught essay writing.

The arguments against the essay as an assessment can be broadly summarised as follows:

- You don't have to write essays in the workplace
- 



