project:
  type: website
  output-dir: _site

website:
  title: "Prof. Emily Nordmann"
  site-url: "https://www.emilynordmann.com/"
  navbar:
    left:
      - text: "Blog"
        href: post.qmd
      - text: "Contact"
        href: contact.qmd
      - text: "CV"
        href: files/cv.pdf

format:
  html:
    theme: cosmo
    toc: false
    css: styles.css

execute:
  freeze: auto

# copy over common asset folders if you have them
resources:
  - "images/**"
  - "files/**"
