project:
  type: website
  output-dir: _site

website:
  title: "Emily Nordmann"
  site-url: "https://www.emilynordmann.com/"
  navbar:
    left:
      - text: "Blog"
        href: post.qmd
      - text: "Contact"
        href: contact.qmd
      - text: "CV"
        href: files/cv.pdf

format:
  html:
    toc: false
    css: styles.css
    theme:
      light: cosmo    # current light theme
      dark: slate    # or darkly, slate, etc.
    toggle: true

execute:
  freeze: auto

# copy over common asset folders if you have them
resources:
  - "images/**"
  - "files/**"
