---
title: "Reflections on Rainbow Office Hours"
author: "Emily Nordmann"
date: 2026-04-20
categories: [education, learning and teaching, evidence-based practice]
image: https://media.licdn.com/dms/image/v2/D4E12AQGb_UttDmyZYQ/article-cover_image-shrink_720_1280/B4EZdEf7_RHgAU-/0/1749200913006?e=2147483647&v=beta&t=H56PshmQr4UuP85et7_HStSd89RasZ7dgpFdhE9uT4I 
---

This blog is inspired by having recently read [Exploring Staff Experiences of Rainbow Office Hours: An LGBTQIA+ Inclusive Initiative in Higher Education—“I’m Gay at Home, but I’m also Gay at Work](https://www.mdpi.com/2076-0760/15/4/216) by [Sarah McHiller]() and colleagues at the University of Bournemouth.  Whilst ROH started at Glasgow, we have entirely dropped the ball in properly studying and writing it up and whilst I'm not going to pretend there isn't a sliver of jealousy and annoyance at myself that's it's not my name on the first paper about it, more than anything what I think is that this is an important, timely, and well-written paper that I am incredibly pleased has been published As I am about to write about, I don't agree with all of it, but that doesn't change my respect for the work and you should add it to your reading list with some priority. 

But first a trip down memory lane.



