---
title: 'ChatGPT: Student guidance for essays'
author: Emily Nordmann
date: '2023-08-01'
slug: chatgpt-student-guidance-for-essays
categories:
  - chatgpt
tags:
  - chatgpt
---

Part 1: [Using ChatGPT to create teaching materials: Data simulation & MCQs](https://www.emilynordmann.com/post/using-chatgpt-to-create-teaching-materials-data-simulation-mcqs/)

Part 2: [Using ChatGPT to create teaching materials: marking criteria & rubrics](https://www.emilynordmann.com/post/using-chatgpt-for-teaching-marking-criteria-rubrics/)

Part 3: [ChatGPT: Student guidance for multiple-choice assessments](https://www.emilynordmann.com/post/chatgpt-student-guidance-for-mulitple-choice-assessments/)

Part 4: [Using ChatGPT for learning & teaching: Correcting auto-transcripts](https://www.emilynordmann.com/post/using-chatgpt-for-learning-teaching-correcting-auto-transcripts/)

You could argue that these blogs are an exercise in procrastination and if you spend any time with me in real life, you'll be questioning why I'm writing all these whilst constantly moaning about workload. If I'm completely honest they are part-procrastination, but, genuinely, I'm much further along than if I hadn't spent the time on these blogs as the process of writing has helped shaped my thoughts.

I've been working on the guidance for my Level 1 essay and in some ways, writing guidance for MCQs was more problematic in that ChatGPT can get them all right very quickly. But in other ways, what is and is not academic misconduct was so clear with MCQs and it's so much harder to draw the lines in the sand when it comes to an essay and provide good advice on how students can and should use AI. I'm so much less sure of myself with the essay guidance. I've structured it under three subheadings although this may well change between now and September (and feedback and ideas are most welcome!). I think it's starting to look ok but my sense of unease remains.


## What use of AI would be regarded as academic misconduct for this assessment?

> Using AI to write any part of your essay for you from scratch is academic misconduct and if we suspect you have used it in this way, we will report you for academic misconduct.

> An easy rule of thumb to follow for the essay is do not copy and paste anything from an AI into your essay. This doesn't avoid every problem, and there are exceptions to the rule, but if you want a simple rule to follow, that's a good starting point.

> Use AI to help you refine and edit your essay, do not use it to write the essay. When in doubt, come and ask talk to us in office hours - you will not get in trouble for asking how to do things right!

It's all shades of grey but I wanted to provide as much clarity as I could. The "don't copy and paste" rule isn't perfect but it probably works well enough to give the right idea. By explicitly noting they may not be sure and could reach out for help, I also wanted to highlight that this isn't an exact art and it's not wrong for them to have questions.

## How can I use AI to help support my learning for this assessment?

> You can use specific AI tools to help with your literature search (but do not use ChatGPT for this! See below for more info):

> Tools like [Elicit](https://elicit.org/search) or [Connected Papers](https://www.connectedpapers.com/) can find relevant papers without perfect keyword match, summarise takeaways from the paper specific to your question, and extract key information from the papers. It's not academic misconduct to use Elicit because you still have to read the papers, understand the information, and integrate it into your essay.

> You can use tools like ChatGPT to get feedback and use it to help you refine and edit (but not write!) your essay. For example, you can use it to get feedback on your draft essay plan. This is a good use of AI because you're using it to get feedback but you're playing an absolutely active role in the creation of your essay.

> **Example prompt**: Act as an expert psychology tutor. I am a first year undergraduate psychology student and have to write an essay on the question [give it your essay question]. Here is the marking criteria [give it the marking criteria]. And here is a draft structure I have written to plan my essay [give it your essay plan]. I want you to give me feedback on how I can improve my essay plan, but before you give any feedback, ask me up to 5 questions about my plan and use my answers to inform your feedback. 

> You can also use it to give you feedback on your draft essay before you submit it. As with using it for feedback on your plan, this is a good use of AI because you're using it in an active way and any changes to your essay will be your own work, you're just getting direction form it. 

> **Example prompt**:  Act as an expert psychology tutor.  am a first year undergraduate psychology student and have to write an essay on the question [give it your essay question].  Here is the marking criteria [give it the marking criteria]. Give me feedback on my essay for each of the marking criteria. 

To test out using it for feedback I got ChatGPT to write me a draft essay plan and essay and then I fed the snake it's own tail and asked for feedback in a new chat window. The feedback it produced was not always up to what a human would produce (although let's face it, that depends on the human) and there's a need to urge caution but as a *supplement* rather than a replacement, I think this would be a useful form of formative feedback - here's an example of the feedback it gave aligned with the marking criteria:

> 3.2 Ensure that the essay has a logical structure and that the paragraphs flow together to form a coherent narrative: The structure of your essay is good, with an introduction, main body, and conclusion. The narrative flow between paragraphs is generally effective, but there are a few places where transitions could be smoother. Additionally, some paragraphs may be too long or too short, affecting the overall coherence of the essay. Consider reorganizing and editing for better flow and readability.

It is quite general but I would prefer general to overly specific and the important thing here is that ChatGPT isn't doing any of their work, they still have to action the feedback. I would also be really interested to know if there's a difference in how students respond to AI vs human feedback - I would imagine they'd be more likely to assume the human was right but also coming from an AI probably strips the feedback of its emotion which might make them more likely to process it? Interesting times ahead.

I also wanted to address the use of ChatGPT for editing. Most of my thoughts on this came out of trying to use it for [correcting auto-transcripts](https://www.emilynordmann.com/post/using-chatgpt-for-learning-teaching-correcting-auto-transcripts/) where I really struggled to get it to do exactly what I wanted. My key concern here is students giving it their essay and then whether they wanted it to or not, ChatGPT editing the entire thing and changing the meaning of what they've written and stripping their writing of any individuality. I want them to make active, conscious choices and to learn from the editing process not just take what it gives them without thinking.

> Finally, you can use it to help you proof-read and edit. Be very careful to ask it to provide you with line-by-line changes with the comparison so that you can see what it has changed and why, because it means you're making an active choice and it will also help you learn about how to improve your writing. 

> Before you use AI for editing, remember that it is important that you develop your own voice as a writer and if you constantly use AI to edit you'll end up with a bland, generic writing style. If everyone does this we're going to end up with a world written in beige. Don't be beige. Also remember that just because the AI suggests an edit, doesn't mean it is better than what you've written! Even with the below prompts it may edit more than you ask it to  - if it does this and edits huge paragraphs rather than individual sentences, ignore it and click regenerate response - you want it to give you the edits line-by-line so that you can compare them and choose the ones you think are actually an improvement.

> **Example prompt**: Act as an expert academic writing tutor. I have written an undergraduate university essay and I would like you to review it with regards to spelling, grammar, concise writing, APA formatting, and academic tone. Provide suggestions for edits I can make sentence-by-sentence. Provide the original and your edited suggestion so that I can compare them. Explain why you have suggested the edit [give it your essay]:

> **Example prompt if English is not your first language**:  Act as an expert academic writing tutor. My first language is [your first language]. I have written an undergraduate university essay and I would like you to review it with regards to ensuring that the writing follows the grammar rules and conventions of British English. Provide suggestions for edits I can make sentence-by-sentence. Provide the original and your edited suggestion so that I can compare them. Explain why you have suggested the edit [give it your essay]

I am  terrified that I am pointing them towards a tool that will potentially harm their development as writers, either because they will blindly copy and paste and end up changing the meaning of what they intended, or that we'll end up in a world where everyone has the same generic A-corrected writing.  

But, abstinence as a policy isn't going to work - if we don't guide them they're going to do it anyway, my logic here is that at least this way I can make them aware of the potential pitfalls. 

I am also very likely romanticising the need to develop an individual writing voice based on my own feelings about writing. As I write this I've got George Orwell's [rules for writing](https://sites.duke.edu/scientificwriting/orwells-6-rules/) swirling around in my head, the fact that I know them by heart should tell me I might have crossed the line into wanky academic. Maybe losing some individuality is the price we pay for massively improving the clarity of most people's writing (I vehemently don't believe this but I feel like I should at least provide the other side of the argument)?. 

## What are the limitations of using AI for this assessment and what should I be careful of aside from academic misconduct?

In addition to the above caveats, I have a standard heading about limitations to try and get them thinking more critically about AI and not just focus on the issue of misconduct.

> Do not use AI tools like ChatGPT to do your research. Use tools like Scopus, Web of Science, Google Scholar, ad Elicit and read the papers yourself. The reasons for this are that:
a) if you rely on AI summaries you won't develop the depth of understanding you need at university level and your essay will be shallow 
b) reading papers helps you develop an academic tone in your writing 
c) sometimes it tells you things that are simply wrong, including making up references that don't exist
d) it doesn't have access to the most recent research.

> If you use it for feedback, it may give you advice that isn't very good and if you're not super careful about ensuring you've given it all the guidance from the labs and your tutor, it may end up telling you to do something that contradicts what we've told you to do. If you do use AI to help refine your structure, we'd strongly encourage you to come to office hours or GTA sessions to check you're on the right track. 

> AI writing is frequently formulaic, uninspiring, and often doesn't have the right tone.

> When you ask it to suggest edits for your work, you have to be really careful to review its suggestions because sometimes it will change the core meaning of what you've written rather than just correcting the grammar or tone. Always ask it to give you suggestions sentence-by-sentence and if it doesn't do this, try changing the prompt or regenerate the response until it does. Remember that your version might be better than than the AI - trust yourself!

> Another use case we've seen is using AI to correct your references into APA formatting, but having tried this, it didn't do a very good job so we'd suggest using a reference manager like Zotero instead if you want something to help automate that process (although you still need to check them).

Is this the best approach? I'm not sure. But I am fairly sure that right now, at scale, honesty and transparency is the only tool we've got that's of any use. I know that some students will abuse it, and some will likely take my guidance to abuse it even more effectively. But I have always believed that we shouldn't design learning & teaching around the lowest common denominator and that the overwhelming majority of students want to, and do, do things as intended so we should give them what information we do have whilst we're still figuring it out on our side.

God I hope I'm right.

---------------------------------------------------------

About halfway through writing this blog I got the song "Walk through the fire" from the Buffy musical stuck in my head like the millennial I am so let's end with that.

*Will this do a thing to change it?*
*Am I leading them to danger?*
*Are we all too far gone to care?*

<iframe width="560" height="315" src="https://www.youtube.com/embed/5iyM6nDt5g8" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>







