---
title: 'Pivot 2: Academic, heal thyself'
author: Emily Nordmann
date: '2020-07-24'
slug: pivot-2
---

> The problem with starting your first blog with a pithy quote is that you feel pressured to do it for every one.

I thought I was going to have to start this blog by admitting that I hadn't actually done much pivot work this week - I spent the first half of the week working on assessment stuff that has nothing to do with the change in delivery and is just part of the usual yearly updates and tweaks. And then I realised that it's completely the wrong way to look at it.

In our [10 Simple Rules*](https://psyarxiv.com/qdh25) paper, we make the point (helpfully suggested by [Simon Horrocks](https://twitter.com/horrocks_simon)) that *For courses that already involve substantial use of the VLE and online content, it can be helpful to highlight that the pivot may be more accurately described as blended to online, rather than offline to online*. 

Academic, heal thyself.

This week I updated the essay question and guidance** for the first year coursework essay and that's just as much a part of the pivot as designing and recording asynchronous lab activities will be. This week was a good reminder that whilst a part of what I need to do is completely new and terrifying, the majority is the same work, or an adaptation of the same work I would usually do in the summer. 

## Group presentation, but make it COVID

One of the few assessments we have that needed more than minor tweaks was a group presentation that would normally be given in the final lab of the semester. The topic is "What three things would you tell yourself as a new level 1 student if you could hit rewind?" and students are asked to reflect on their first semester at university and what they would do differently. The entire thing has to be evidence-based and they draw on what they've learned about things like memory, learning, sleep, mental health, and study strategies from the lectures in addition to doing their own research. It's a wonderful lab for many reasons - the presentations are funny, insightful, heart-warming, heart-breaking, and academically rigorous. Given that their first semester is going to be very different to what they expected from university life, we are very keen to retain the topic to give them a chance to reflect on all they have achieved and experienced.

They will still work in groups and the topic will remain the same, but rather than a 10-minute presentation they will be given the choice between a 5-minute video, a blogpost, or a infographic poster. I stole this idea (and some of the learning outcomes and guidance) from my colleague Chiara Horlin's Professional Skills course. This is a Level 3 science communication assessment so the scale and expectations are slightly different to my Level 1 adaptation but the core message here is to remember that there's loads of good practice out there waiting to be appropriated. If you don't know how to adapt your course or assessments, ask your colleagues, ask your educational development team, hell, ask on Twitter.

For this assessment I've given more guidance than I normally would, particularly when it comes to scaffolding the group-work because it is my firm belief that for 1st years this September, if it feels like spoon-feeding*** you're probably doing it right. It's still a bit of a work in-progress but the [assessment information is here](https://sway.office.com/FGayGVQz6wAPxg3u?ref=Link) if you'd like to take a look.

From a technological perspective I'm hyper-aware that I have to provide suggestions for collaborative and creative tools that they can access freely. Their Office 365 package solves a lot of this - OneDrive, Word, PowerPoint and Sway cover a lot of bases but I've also tried to find alternatives, particularly for video recording and editing (Zoom, Animaker, InShot) and infographics (Canva).

## Student consultation

This week I also hosted a consultation with teaching staff and GTAs where I invited 2019-2020 first year students to feedback on our plans for blended delivery for first year 2020-2021 given that they experienced the old-normal version of the course. Not too many turned up (to be fair to them, it's July, they're scattered all over the world, and their focus will be on what Level 2 will look like) but it was really useful to hear from those that did. 

They were largely happy with our plans and were understanding of the constraints and uncertainty we're working under, but the main thing I took away from the session is how important it was to be able to explain not only what we are planning, but why. It's a level of detail regarding the underlying rationale and administration for teaching that we wouldn't necessarily normally communicate**** but I think it was really helpful for them to understand the scope of everything we've had to consider when designing the course. We've recorded the session and I have sent it out in case those who couldn't make it are interested.

My contact with incoming student is still relatively limited but we do have a Facebook group which will slowly fill up as more of them confirm their offers and finalise their decisions. They've already been provided with an information and FAQ pack but I've given them an anonymous form to ask any questions or write down anything they're worried about with the view of doing a Q&A video in the next couple of weeks.

Next week I will continue working on assessment information and specifications. For level 1 I need to finish a few details and then move on to doing the same for my MSc conversion Research Methods course. If I have time, I'll also start to write the mother of all week-by-week roadmaps for all of the learning activities for both lecture and labs.


\* Yes, I am going to mention this paper in every blog because it's great.  
** I think we've designed a great essay btw, you can check it out [here](https://www.emilynordmann.com/project/missing_history/).  
*** It is also my firm belief that what most of what is derogatively described as spoon-feeding is actually clearly signposted information that gives students the information they need to succeed without chance.  
**** We're very open with our students and strongly believe in the power of co-creation, but room capacities and the definition of asynchronous and didactic teaching don't often come up.  

